In [1]:
import numpy as np

In [2]:
#input 3 channels:x_0,x_1 and x_2
x_0=np.array([[0,3,2,6,1],[7,6,7,5,7],[4,1,4,0,3],[3,5,2,6,5],[7,0,7,5,1]])
x_1=np.array([[1,2,6,1,0],[3,6,0,5,1],[0,1,1,3,0],[6,1,5,2,3],[1,0,1,5,0]])
x_2=np.array([[3,0,2,3,4],[1,5,4,0,1],[6,2,6,2,5],[1,0,5,7,1],[5,3,7,3,0]])
# 3 filters: w_0,w_1,w_2
w_0=np.array([[1,0,1],[-1,0,0],[-1,1,1]])
w_1=np.array([[1,1,1,],[-1,-1,1],[1,-1,0]])
w_2=np.array([[1,1,0],[-1,1,-1],[1,1,-1]])
inp_w=np.array([[x_0,w_0],[x_1,w_1],[x_2,w_2]])

In [20]:
final_ans=np.array([[0]*3 for x in range(3)])
for z in range(3):
    #assigning imput matrix and weight to be used in this iteration
    x,w=inp_w[z][0],inp_w[z][1]
    #initialing 3*3 array to store output of each stride dot product 
    ans=np.array([[0]*3 for x in range(3)])
    for i in range(3):
        for j in range(3):
            temp=np.multiply(x[i:i+3,j:j+3],w)
            ans[i][j]=temp.sum()
    
    #adding 3 resultunt matrices element wise
    final_ans+=ans
    #print(ans)
    
#adding bias to final ans
print('Output matrix : \n',final+1)

Output matrix : 
 [[ 1 22  0]
 [21 31 31]
 [10 22 20]]
